#!/bin/sh

if [ "$1" = "get" ]; then
    if [ -z "$GIT_USERNAME" ] || [ -z "$GIT_PASSWORD" ]; then
        printf 'error: GIT_USERNAME and GIT_PASSWORD must be set\n' >&2
        exit 1
    else
        printf 'username=%s\npassword=%s\n' "$GIT_USERNAME" "$GIT_PASSWORD"
    fi
fi
